# Use postgres/example user/password credentials
version: '3.1'

services:
  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  mssqldb:
      image: mcr.microsoft.com/mssql/server:2017-latest
      restart: always
      environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: d3m0p@ssw0rd
      ports:
        - 1433:1433

